# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YmRlOGFlOTkwMTI0ODRlZTVjN2Y4MWM1ODU2NzJiZGU1NGI3YjU4ODVjNWM4ZDQ2MTM1ZTMyOGUzMmU2ZTYwOGQ1NDkxMTExOWQ5NGMzMTUzZTQwZWYxYWVlOTZkZTk1MTk1ZjZjYWI4NWM0ZWQ2MWY3OWI0MDQ0ZDcwYTI5NDc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
