# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MDU4NjBlMjY0ODcxOWZiZDYwZTBlMTVmMDkwY2FiNmMyZGUyYjM3ZTZlZGIzZjY2MGFiNmU2YmNiMjRiNzA2YjVlYzQzZDJkY2JiNDM4MmQ4ZWMyNmVlMjhkYTMyNThjNWFhZWZmYzI0MDAwOTk2MmM0NDI5YjM1YzAxMjQ1ZTk=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
